### PR TITLE
dankify react thug

### PR DESCRIPTION
**Pull request by evinism**
love this project. this is likely merely an oversight, so i fixed it right up for ya :)

### CODE REVIEW

**Review by michaelstephens — CHANGES_REQUESTED** [review]
Can the iFunny watermark be bigger? I find my eye isn't drawn enough to it.

**Comment by erikras** [comment]
Can you explain how this is an improvement?

**Comment by evinism** [comment]
oh you're totally right, I was way off base with that. this is much better:

lolol2

**Comment by erikras** [comment]
Aha. I get it now. 👍

However, I think I'll let you keep that version on your fork.

**Pull request closed without merging**
